version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - mynetwork

  node:
    build: .
    volumes:
      - ./your/node/app:/app
    networks:
      - mynetwork

volumes:
  jenkins_data:

networks:
  mynetwork:
